import turtle as t

def triangle(x, y, a,
             destination, color):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color(color)
    t.fillcolor(color)
    t.begin_fill()
    # позиция 1-4 похожи на координатные четверти, попробуйте вывести
    if destination == 1:
        t.forward(a)
        t.goto(x, y)
        t.left(90)
        t.forward(a)
        t.right(135)
        t.forward((a ** 2 * 2) ** 0.5)
    elif destination == 2:
        t.left(90)
        t.forward(a)
        t.goto(x, y)
        t.left(90)
        t.forward(a)
        t.right(135)
        t.forward((a ** 2 * 2) ** 0.5)
    elif destination == 3:
        t.right(180)
        t.forward(a)
        t.goto(x, y)
        t.left(90)
        t.forward(a)
        t.right(135)
        t.forward((a ** 2 * 2) ** 0.5)
    elif destination == 4:
        t.forward(a)
        t.goto(x, y)
        t.right(90)
        t.forward(a)
        t.left(135)
        t.forward((a ** 2 * 2) ** 0.5)
    # позиция где прямой угол смотрит влево
    elif destination == 5:
        t.right(45)
        t.forward(a)
        t.goto(x, y)
        t.left(90)
        t.forward(a)
        t.right(135)
        t.forward((a ** 2 * 2) ** 0.5)
    # прямой смотрит вправо
    elif destination == 6:
        t.left(180)
        t.left(45)
        t.forward(a)
        t.goto(x, y)
        t.right(90)
        t.forward(a)
        t.left(135)
        t.forward((a ** 2 * 2) ** 0.5)
    # смотрит вверх
    elif destination == 7:
        t.right(45)
        t.forward(a)
        t.goto(x, y)
        t.right(90)
        t.forward(a)
        t.left(135)
        t.forward((a ** 2 * 2) ** 0.5)
    # смотрит вниз
    elif destination == 8:
        t.left(45)
        t.forward(a)
        t.goto(x, y)
        t.left(90)
        t.forward(a)
        t.right(135)
        t.forward((a ** 2 * 2) ** 0.5)
    t.penup()
    t.end_fill()
    t.setheading(to_angle=0)


def trapezoid(x, y, a, b,
              height, placement, color):
    # x, y - левый верхний угол, a - меньшее основание, b - большее
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color(color)
    t.fillcolor(color)
    # меньшее основание сверху
    if placement == 1:
        t.begin_fill()
        t.forward(a)
        t.right(90)
        t.penup()
        t.forward(height)
        t.pendown()
        t.left(90)
        t.forward((b - a) / 2)
        t.goto(x + a, y)
        t.right(90)
        t.penup()
        t.forward(height)
        t.pendown()
        t.right(90)
        t.forward((b + a) / 2)
        t.goto(x, y)
        t.end_fill()
    # большее основание сверху
    elif placement == 2:
        t.forward(b)
        t.right(90)
        t.penup()
        t.forward(height)
        t.right(90)
        t.forward((b - a) / 2)
        t.pendown()
        t.forward(a)
        t.begin_fill()
        t.goto(x, y)
        t.goto(x + b, y)
        t.left(t.towards(x + ((b + a) / 2), y - height))
        t.backward((((b - a) / 2) ** 2 + height ** 2) ** 0.5)
        t.end_fill()
    # меньшее основание слева
    elif placement == 3:
        t.right(90)
        t.forward(a)
        t.left(90)
        t.penup()
        t.forward(height)
        t.pendown()
        t.begin_fill()
        t.right(90)
        t.forward((b - a) / 2)
        t.goto(x, y - a)
        t.goto(x, y)
        t.left(90)
        t.penup()
        t.forward(height)
        t.pendown()
        t.left(90)
        t.forward((b - a) / 2)
        t.goto(x, y)
        t.penup()
        t.right(90)
        t.forward(height)
        t.pendown()
        t.right(90)
        t.forward((b + a) / 2)
        t.end_fill()
    # меньшее основание справа
    elif placement == 4:
        t.right(90)
        t.forward(b)
        t.left(90)
        t.penup()
        t.forward(height)
        t.left(90)
        t.forward((b - a) / 2)
        t.begin_fill()
        t.pendown()
        t.forward(a)
        t.goto(x, y)
        t.right(180)
        t.forward(b)
        t.goto(x + height, y - ((b + a) / 2))
        t.end_fill()
    t.penup()
    t.setheading(to_angle=0)


def square(x, y, a,
           alpha, color):
    # alpha-угол поворота вокруг (x,y)
    t.fillcolor(color)
    t.pencolor(color)
    t.begin_fill()
    t.up()
    t.goto(x, y)
    t.down()
    t.right(alpha)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(a)
    # привожу стрелку в дефолтное положение
    t.right(90 - alpha)
    t.up()
    t.end_fill()

def ornament(i):
    triangle(0 + 100 * i,0,25,4,"MediumPurple2")
    trapezoid(25 + 100 * i,0,25,75,25,1,"Plum4")
    triangle(100 * i + 75,0,25,3,"MediumPurple2")
    square(100 * i + 75,0,25,0,"LightSteelBlue")

for i in range(0,3):
    ornament(i)